### ISSUE TITLE
Android Gradle Plugin Update Recommended

### ISSUE THREAD

**Issue by stuartsoft** [madebyatomicrobot/android-starter-project#19]
![image](https://cloud.githubusercontent.com/assets/6208902/23393838/91220004-fd53-11e6-87d6-12a8963503b9.png)

**Comment by patrickhammond** [comment]
We need to go through and update the Gradle version, plugin version, build tool versions, etc to all the latest.  I've been waiting for the next version of Android Studio, et. al. to go stable first though.

**Comment by weverb2** [comment]
@patrickhammond 2.3 is out :) want to go ahead with this?

**Comment by patrickhammond** [comment]
@weverb2 Absolutely!

**Comment by weverb2** [comment]
Fixed in #22
