### ISSUE TITLE
Adopt mockk

### ISSUE THREAD

**Issue by patrickhammond** [madebyatomicrobot/android-starter-project#73]
Now that we are all in on Kotlin, it makes sense to move over to something as nice as mockito with better sugar in Kotlin. @weverb2 is this something you are interested in? Anything we should be aware of?

**Comment by weverb2** [comment]
I think the main problem would be Dagger Mock.

**Comment by patrickhammond** [comment]
Hmm...Dagger/Espresso integration is still listed on their backlog.
https://github.com/mockk/mockk/blob/master/BACKLOG.md
